### ISSUE TITLE
how to clear the matrix screen

### ISSUE THREAD

**Issue by mokun** [HanSolo/dotmatrix#2]
Is there a quick way to clear the previous text sent to the matrix ?

I added the following method in DotMatrix but it doesn't work
```
    public void clear() {
        ctx.clearRect(0, 0, width, height);
    }
```
I'd like to clear out the matrix screen so that I may send a new message down the pipeline.

**Comment by HanSolo** [comment]
You can either switch each pixel separately on/off in a loop by using setPixel(x, y, true/false) or simply use the setAllDotsOff() method.
