### ISSUE TITLE
how to buffer new messages

### ISSUE THREAD

**Issue by mokun** [HanSolo/dotmatrix#3]
Thanks for this wonderful library made available for people to play with.

Suppose I use DotMatrix as a breaking news marque banner like what we see in CNN. 

Say we may have successive messages that we need to send to this news banner.

What I have tried to do is to first stop the timer and set it to null, then I create a new timer for the new message as follows : 

```
	public void sendMsg(String str) {
   
		if (!str.equals(messageCache)) {
			
	        if (billboardTimer != null) {
	        	matrix.clear();
	        	billboardTimer.stop();
	        	billboardTimer = null;
	        }
	        
			messageCache = str;
			
			newsHeader = null;
			if (str.contains("died"))
				newsHeader = BREAKING_NEWS;
			else if (str.contains("suffered") || str.contains("cured"))
				newsHeader = HEALTH_NEWS;
			else if (str.toLowerCase().contains("mission"))
				newsHeader = MISSION_REPORTS;
			else if (str.toLowerCase().contains("radiation"))			
				newsHeader = HAZARD;
			else
				newsHeader = BREAKING_NEWS;
	
			String text = newsHeader + str.;
	        textLength = text.length();
	        textLengthInPixel = textLength * 8;
		    offset = 3;
		    x = matrix.getCols() + 7;
	        lastTimerCall = System.nanoTime();
	        
	        billboardTimer = new AnimationTimer() {
	            @Override public void handle(final long now) {
	                if (now > lastTimerCall + 10_000_000l) {
	                    if (x < -textLengthInPixel) {
	                      x = matrix.getCols() + 7;
	                    }
	                    int color = RED;
	                    if (newsHeader.equals(MISSION_REPORTS))
	                    	color = LIME;
	                    else if (newsHeader.equals(HEALTH_NEWS))
	                    	color = YELLOW;
	                    else if (newsHeader.equals(HAZARD))
	                    	color = ORANGE;
	                    for (int i = 0 ; i < textLength ; i++) {
	                        matrix.setCharAt(text.charAt(i), x + i * 8, offset, color);
	                    }
	                    x--;
	                    lastTimerCall = now;
	                }
	            }
	        };
	        billboardTimer.start();
		}
	}
```

However, the above doesn't give a clean transition between presenting the old message and the new message at all. 

The old message will just stop and linger on the screen and the new message will slowly replace the old one in a rather ugly manner.

So what is the best strategy in implementing a " message buffer" of some sort?

A buffer can contain a list of messages. Any message will stay showing up for only a prescribed amount of time and will expire by itself. If a new message was found in the buffer, the old message will finish up rolling out the rest of the character and then the new message will show up.

**Comment by HanSolo** [comment]
You might want to take a look at the Demo class or just check out the [tilesfx stock demo](https://github.com/HanSolo/tilesfxstockdemo) project. The DotMatrix is a dumb control that simply can switch on/off each of it's pixels with a given color. If you need logic you need to add it separately. With this approach you can use this control for lot's of different things as you can see  [here](https://harmoniccode.blogspot.com/2017/04/friday-fun-xlvi-image-matrix.html), [here](https://harmoniccode.blogspot.com/2017/03/friday-fun-xlv-stockticker.html) or [here](https://harmoniccode.blogspot.com/2017/03/friday-fun-xliv-matrix.html)
